In [1]:
import prosodic as p
import pandas as pd
pd.options.display.max_rows=200

In [2]:
df = pd.read_csv('../data/data.2020.big_data.txt',sep='\t', low_memory=False)

In [3]:
txt = '\n'.join(df.iloc[:1000].prosodic_line)

In [4]:
t = p.Text(txt)
parses = t.parse()

In [12]:
line_parses = t.line1.parses

In [23]:
line_parses.get_df??

Signature: line_parses.get_df(**kwargs)
Docstring: <no docstring>
Source:
    def get_df(self, **kwargs):
        from .parselists import ParseList
        return ParseList(self.data, parse_unit=self.parse_unit, parent=self.parent).get_df(**kwargs)
File:      ~/github/antimetrical/.venv/lib/python3.12/site-packages/prosodic/parsing/vectorized.py
Type:      method

In [28]:
x=p.ParseList([])
x.get_df??

Signature: x.get_df(*args, **kwargs) -> pandas.DataFrame
Source:
    def get_df(self, *args, **kwargs) -> pd.DataFrame:
        """
        Get a DataFrame representation of this ParseList.

        Args:
            *args: Positional arguments.
            **kwargs: Keyword arguments.

        Returns:
            A DataFrame representing this ParseList.
        """
        l = self.unbounded if not self.show_bounded else self.scansions
        l = [p.get_df(*args, **kwargs).reset_index() for p in l]
        return setindex(pd.concat(l), sort=True) if l else pd.DataFrame()
File:      ~/github/antimetrical/.venv/lib/python3.12/site-packages/prosodic/parsing/parselists.py
Type:      method

In [76]:
p.to_dict()

AttributeError: 'NoneType' object has no attribute 'to_dict'

ParseListList([
    <prosodic.parsing.vectorized.LazyParseList object at 0x123700560>
 ])

In [44]:
parses = t.parses

In [45]:
len(parses)

1

In [50]:
t.get_parses_df(mode='all')

,line_num,word_num,form_idx,syll_idx,line_syll_idx,parse_idx,parse_rank,parse_score,is_best,is_bounded,pos_idx,pos_size,meter_val,syll_txt,syll_ipa,is_stressed,*w_peak,*w_stress,*s_unstress,*unres_across
0,1,1,0,0,0,69,1,0.0,True,False,0,2,w,you,juː,False,0,0,0,0
1,1,2,0,0,1,69,1,0.0,True,False,0,2,w,can,kæn,False,0,0,0,0
2,1,3,1,0,2,69,1,0.0,True,False,1,1,s,do,'duː,True,0,0,0,0
3,1,4,0,0,3,69,1,0.0,True,False,2,2,w,more,mɔːr,False,0,0,0,0
4,1,5,0,0,4,69,1,0.0,True,False,2,2,w,than,ðæn,False,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1775,1,6,0,0,5,158,<NA>,14.0,False,True,3,1,w,a,'ɛ,True,1,1,0,0
1776,1,6,0,1,6,158,<NA>,14.0,False,True,4,1,s,ny,niː,False,0,0,1,0
1777,1,7,0,0,7,158,<NA>,14.0,False,True,5,1,w,o,'ə,True,1,1,0,0
1778,1,7,0,1,8,158,<NA>,14.0,False,True,6,1,s,ther,ðɛː,False,0,0,1,0
1779,1,8,1,0,9,158,<NA>,14.0,False,True,7,1,w,in,'ɪn,True,0,1,0,0

In [48]:
parses.bounded

ParseListList([
    ParseList([
        Parse(txt='YOU can DO more.than A ny O ther IN'),
        Parse(txt='you.can DO.MORE than A ny O ther IN'),
        Parse(txt='you.can DO more THAN.A ny O ther IN'),
        Parse(txt='you.can DO more.than A ny O ther.in'),
        Parse(txt='you.can DO more.than A ny O.THER in'),
        Parse(txt='you CAN.DO more.than A ny O ther IN'),
        Parse(txt='you.can DO more.than A.NY o.ther IN'),
        Parse(txt='YOU can DO.MORE than A ny O ther IN'),
        Parse(txt='you.can DO more THAN a.ny O ther IN'),
        Parse(txt='you CAN do MORE than A ny O ther IN'),
        Parse(txt='YOU can DO more.than A ny O.THER in'),
        Parse(txt='YOU can DO more.than A ny O ther.in'),
        Parse(txt='YOU can DO more THAN.A ny O ther IN'),
        Parse(txt='you.can DO more THAN.A ny O ther.in'),
        Parse(txt='you.can DO more THAN.A ny O.THER in'),
        Parse(txt='YOU can DO more.than A.NY o.ther IN'),
        Parse(txt='you CAN.DO more THAN.A ny O ther IN'),
        Parse(txt='you CAN.DO more.than A ny O ther.in'),
        Parse(txt='you.can DO.MORE than A ny O ther.in'),
        Parse(txt='you.can DO.MORE than A ny O.THER in'),
        Parse(txt='you CAN.DO more.than A ny O.THER in'),
        Parse(txt='YOU can.do MORE than A ny O ther IN'),
        Parse(txt='YOU can DO more THAN a.ny O ther IN'),
        Parse(txt='you.can DO more THAN a NY.O ther IN'),
        Parse(txt='you.can DO more THAN a.ny O ther.in'),
        Parse(txt='you CAN.DO more.than A.NY o.ther IN'),
        Parse(txt='YOU can DO.MORE than A ny O ther.in'),
        Parse(txt='you.can DO more.than A ny.o THER in'),
        Parse(txt='you.can DO more.than A ny.o THER.IN'),
        Parse(txt='you.can DO more.than A.NY o THER.IN'),
        Parse(txt='you.can DO more.than A.NY o THER in'),
        Parse(txt='you.can DO.MORE than A.NY o.ther IN'),
        Parse(txt='YOU can DO.MORE than A ny O.THER in'),
        Parse(txt='YOU can DO more THAN.A ny O ther.in'),
        Parse(txt='YOU can DO more THAN.A ny O.THER in'),
        Parse(txt='you.can DO more THAN a.ny O.THER in'),
        Parse(txt='you CAN.DO more THAN a.ny O ther IN'),
        Parse(txt='you CAN do MORE than A ny O ther.in'),
        Parse(txt='you CAN do MORE than A ny O.THER in'),
        Parse(txt='you CAN do.more THAN.A ny O ther IN'),
        Parse(txt='YOU.CAN do MORE than A ny O ther IN'),
        Parse(txt='YOU can DO more THAN a.ny O ther.in'),
        Parse(txt='YOU can DO more THAN a NY.O ther IN'),
        Parse(txt='YOU can DO more THAN a.ny O.THER in'),
        Parse(txt='you CAN do MORE than A.NY o.ther IN'),
        Parse(txt='you.can DO more THAN a NY o.ther IN'),
        Parse(txt='YOU can.do MORE than A ny O.THER in'),
        Parse(txt='YOU can DO more.than A ny.o THER.IN'),
        Parse(txt='YOU can DO more.than A ny.o THER in'),
        Parse(txt='you CAN.DO more THAN.A ny O.THER in'),
        Parse(txt='YOU can.do MORE than A ny O ther.in'),
        Parse(txt='you CAN.DO more THAN.A ny O ther.in'),
        Parse(txt='YOU can DO more.than A.NY o THER.IN'),
        Parse(txt='YOU can DO more.than A.NY o THER in'),
        Parse(txt='YOU can DO.MORE than A.NY o.ther IN'),
        Parse(txt='you CAN do.more THAN a.ny O ther IN'),
        Parse(txt='YOU.CAN do MORE than A ny O ther.in'),
        Parse(txt='you.can DO.MORE than A ny.o THER.IN'),
        Parse(txt='you.can DO.MORE than A ny.o THER in'),
        Parse(txt='you CAN.DO more THAN a NY.O ther IN'),
        Parse(txt='you.can DO.MORE than A.NY o THER in'),
        Parse(txt='you.can DO.MORE than.a NY.O ther IN'),
        Parse(txt='YOU can DO more THAN a NY o.ther IN'),
        Parse(txt='you CAN do MORE.THAN a.ny O ther IN'),
        Parse(txt='YOU.CAN do.more THAN.A ny O ther IN'),
        Parse(txt='you.can DO.MORE than A.NY o THER.IN'),
        Parse(txt='YOU can.do MORE than A.NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE than A ny O.THER in'),
        Parse(txt='you.can DO more THAN.A ny.o THER.IN'),
        Parse(txt='you CAN.DO more THAN a.ny O ther.in'),
        Parse(txt='you CAN do.more THAN.A ny O ther.in'),
        Parse(txt='you CAN.DO more THAN a.ny O.THER in'),
        Parse(txt='you CAN.DO more.than A.NY o THER in'),
        Parse(txt='you CAN.DO more.than A.NY o THER.IN'),
        Parse(txt='you.can DO more THAN a NY.O ther.in'),
        Parse(txt='you CAN.DO more.than A ny.o THER in'),
        Parse(txt='you.can DO more THAN.A ny.o THER in'),
        Parse(txt='you CAN do.more THAN.A ny O.THER in'),
        Parse(txt='you CAN.DO more.than A ny.o THER.IN'),
        Parse(txt='YOU can DO more THAN a NY.O ther.in'),
        Parse(txt='you CAN do MORE than A.NY o THER in'),
        Parse(txt='YOU can DO more THAN.A ny.o THER in'),
        Parse(txt='you CAN do MORE than A.NY o THER.IN'),
        Parse(txt='you CAN do MORE than A ny.o THER in'),
        Parse(txt='you CAN do MORE than A ny.o THER.IN'),
        Parse(txt='you CAN.DO more THAN a NY o.ther IN'),
        Parse(txt='YOU can DO more THAN.A ny.o THER.IN'),
        Parse(txt='YOU can DO.MORE than A ny.o THER.IN'),
        Parse(txt='you.can DO more THAN a NY o THER.IN'),
        Parse(txt='YOU can DO.MORE than A ny.o THER in'),
        Parse(txt='you.can DO.MORE than.a NY o.ther IN'),
        Parse(txt='YOU can DO.MORE than A.NY o THER.IN'),
        Parse(txt='YOU can DO.MORE than A.NY o THER in'),
        Parse(txt='YOU.CAN do.more THAN a.ny O ther IN'),
        Parse(txt='you CAN do.more THAN a.ny O.THER in'),
        Parse(txt='you CAN do.more THAN a.ny O ther.in'),
        Parse(txt='you CAN do.more THAN a NY.O ther IN'),
        Parse(txt='you CAN do MORE than.a NY.O ther IN'),
        Parse(txt='you.can DO more THAN a NY o THER in'),
        Parse(txt='YOU.CAN do MORE than A.NY o.ther IN'),
        Parse(txt='YOU can DO.MORE than.a NY.O ther IN'),
        Parse(txt='YOU can.do MORE.THAN a.ny O ther IN'),
        Parse(txt='YOU can.do MORE than.a NY.O ther IN'),
        Parse(txt='YOU can.do MORE than A.NY o THER in'),
        Parse(txt='YOU can DO.MORE than.a NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE.THAN a.ny O ther IN'),
        Parse(txt='YOU can.do MORE than A.NY o THER.IN'),
        Parse(txt='YOU can.do MORE than A ny.o THER in'),
        Parse(txt='YOU.CAN do.more THAN.A ny O.THER in'),
        Parse(txt='YOU can.do MORE than A ny.o THER.IN'),
        Parse(txt='YOU.CAN do.more THAN.A ny O ther.in'),
        Parse(txt='YOU can DO more THAN a NY o THER.IN'),
        Parse(txt='you CAN do MORE than.a NY o.ther IN'),
        Parse(txt='you CAN do MORE.THAN a.ny O.THER in'),
        Parse(txt='you CAN do.more THAN a NY o.ther IN'),
        Parse(txt='you CAN.DO more THAN.A ny.o THER.IN'),
        Parse(txt='you CAN do MORE.THAN a.ny O ther.in'),
        Parse(txt='you CAN.DO more THAN a NY.O ther.in'),
        Parse(txt='you CAN.DO more THAN.A ny.o THER in'),
        Parse(txt='you CAN do MORE.THAN a NY.O ther IN'),
        Parse(txt='YOU can DO more THAN a NY o THER in'),
        Parse(txt='you.can DO.MORE than.a NY.O ther.in'),
        Parse(txt='YOU can.do MORE.THAN a.ny O ther.in'),
        Parse(txt='YOU.CAN do MORE than A.NY o THER in'),
        Parse(txt='YOU can.do MORE.THAN a NY.O ther IN'),
        Parse(txt='you CAN do MORE than.a NY.O ther.in'),
        Parse(txt='YOU.CAN do MORE than A ny.o THER in'),
        Parse(txt='YOU.CAN do.more THAN a.ny O.THER in'),
        Parse(txt='YOU.CAN do MORE than A.NY o THER.IN'),
        Parse(txt='YOU can.do MORE.THAN a.ny O.THER in'),
        Parse(txt='YOU can.do MORE than.a NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE than A ny.o THER.IN'),
        Parse(txt='YOU.CAN do.more THAN a NY.O ther IN'),
        Parse(txt='you CAN do MORE.THAN a NY o.ther IN'),
        Parse(txt='you CAN do.more THAN a NY.O ther.in'),
        Parse(txt='you CAN do.more THAN.A ny.o THER.IN'),
        Parse(txt='you CAN do.more THAN.A ny.o THER in'),
        Parse(txt='you CAN.DO more THAN a NY o THER.IN'),
        Parse(txt='you CAN.DO more THAN a NY o THER in'),
        Parse(txt='YOU can DO.MORE than.a NY.O ther.in'),
        Parse(txt='YOU.CAN do MORE than.a NY.O ther IN'),
        Parse(txt='you.can DO.MORE than.a NY o THER.IN'),
        Parse(txt='you.can DO.MORE than.a NY o THER in'),
        Parse(txt='YOU.CAN do.more THAN a.ny O ther.in'),
        Parse(txt='YOU.CAN do.more THAN a NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE.THAN a.ny O.THER in'),
        Parse(txt='YOU.CAN do MORE than.a NY o.ther IN'),
        Parse(txt='you CAN do MORE.THAN a NY.O ther.in'),
        Parse(txt='YOU.CAN do MORE.THAN a.ny O ther.in'),
        Parse(txt='YOU can.do MORE than.a NY.O ther.in'),
        Parse(txt='you CAN do MORE than.a NY o THER in'),
        Parse(txt='you CAN do MORE than.a NY o THER.IN'),
        Parse(txt='you CAN do.more THAN a NY o THER.IN'),
        Parse(txt='you CAN do.more THAN a NY o THER in'),
        Parse(txt='YOU can DO.MORE than.a NY o THER in'),
        Parse(txt='YOU can DO.MORE than.a NY o THER.IN'),
        Parse(txt='YOU can.do MORE.THAN a NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE.THAN a NY.O ther IN'),
        Parse(txt='YOU.CAN do.more THAN a NY.O ther.in'),
        Parse(txt='you CAN do MORE.THAN a NY o THER.IN'),
        Parse(txt='YOU.CAN do.more THAN.A ny.o THER.IN'),
        Parse(txt='YOU.CAN do MORE.THAN a NY o.ther IN'),
        Parse(txt='YOU.CAN do MORE than.a NY.O ther.in'),
        Parse(txt='you CAN do MORE.THAN a NY o THER in'),
        Parse(txt='YOU can.do MORE.THAN a NY.O ther.in'),
        Parse(txt='YOU can.do MORE than.a NY o THER in'),
        Parse(txt='YOU can.do MORE than.a NY o THER.IN'),
        Parse(txt='YOU.CAN do.more THAN.A ny.o THER in'),
        Parse(txt='YOU.CAN do.more THAN a NY o THER.IN'),
        Parse(txt='YOU.CAN do.more THAN a NY o THER in'),
        Parse(txt='YOU.CAN do MORE than.a NY o THER in'),
        Parse(txt='YOU.CAN do MORE than.a NY o THER.IN'),
        Parse(txt='YOU can.do MORE.THAN a NY o THER in'),
        Parse(txt='YOU can.do MORE.THAN a NY o THER.IN'),
        Parse(txt='YOU.CAN do MORE.THAN a NY.O ther.in'),
        Parse(txt='YOU.CAN do MORE.THAN a NY o THER in'),
        Parse(txt='YOU.CAN do MORE.THAN a NY o THER.IN')
  ])
 ])